import MembersView from '@components/members/Members';
import ThematicMap from '@components/thematicMap/ThematicMap';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto px-[5%]">
        {/* thematic map */}
        <ThematicMap />

        {/* members */}
        <MembersView />
      </main>
    </div>
  );
}
